### ISSUE TITLE
Одна сборка

### ISSUE THREAD

**Issue by tugibaev** [garakh/kladrapi-dotnet#1]
Было бы хорошо интегрировать обработчик JSON в сборку, чтобы не "носить" с проектом лишние сборки.

**Comment by lanserxt** [comment]
А если выйдет новая версия Json.NET?

**Comment by tugibaev** [comment]
Думаю  - наплевать, если будет работать kladrapi-dotnet. В бизнес приложениях (которым является kladrapi как компонент) места гикам - нет.

**Comment by tugibaev** [comment]
Спасибо. Проект больше не интересен.

**Comment by lanserxt** [comment]
Столько лет прошло )
